### YamlMime:ManagedReference
items:
- uid: Opticon.OpnEnvironment.OpnDebugMode
  commentId: T:Opticon.OpnEnvironment.OpnDebugMode
  id: OpnEnvironment.OpnDebugMode
  parent: Opticon
  children:
  - Opticon.OpnEnvironment.OpnDebugMode.Basic
  - Opticon.OpnEnvironment.OpnDebugMode.Off
  - Opticon.OpnEnvironment.OpnDebugMode.Verbose
  langs:
  - csharp
  - vb
  name: OpnEnvironment.OpnDebugMode
  nameWithType: OpnEnvironment.OpnDebugMode
  fullName: Opticon.OpnEnvironment.OpnDebugMode
  type: Enum
  source:
    id: OpnDebugMode
    path: C:\OPN2001\CSP2\Windows\M3188 .Net Wrapper\source\Csp2.net\Opticon.csp2.net\OpnEnvironment.cs
    startLine: 79
  assemblies:
  - Opticon.csp2
  namespace: Opticon
  summary: Specifies the debug mode for the CSP2 library.
  example: []
  syntax:
    content: public enum OpnEnvironment.OpnDebugMode
    content.vb: Public Enum OpnEnvironment.OpnDebugMode
- uid: Opticon.OpnEnvironment.OpnDebugMode.Off
  commentId: F:Opticon.OpnEnvironment.OpnDebugMode.Off
  id: Off
  parent: Opticon.OpnEnvironment.OpnDebugMode
  langs:
  - csharp
  - vb
  name: Off
  nameWithType: OpnEnvironment.OpnDebugMode.Off
  fullName: Opticon.OpnEnvironment.OpnDebugMode.Off
  type: Field
  source:
    id: Off
    path: C:\OPN2001\CSP2\Windows\M3188 .Net Wrapper\source\Csp2.net\Opticon.csp2.net\OpnEnvironment.cs
    startLine: 82
  assemblies:
  - Opticon.csp2
  namespace: Opticon
  summary: Debugging disabled.
  example: []
  syntax:
    content: Off = 0
    return:
      type: Opticon.OpnEnvironment.OpnDebugMode
- uid: Opticon.OpnEnvironment.OpnDebugMode.Basic
  commentId: F:Opticon.OpnEnvironment.OpnDebugMode.Basic
  id: Basic
  parent: Opticon.OpnEnvironment.OpnDebugMode
  langs:
  - csharp
  - vb
  name: Basic
  nameWithType: OpnEnvironment.OpnDebugMode.Basic
  fullName: Opticon.OpnEnvironment.OpnDebugMode.Basic
  type: Field
  source:
    id: Basic
    path: C:\OPN2001\CSP2\Windows\M3188 .Net Wrapper\source\Csp2.net\Opticon.csp2.net\OpnEnvironment.cs
    startLine: 85
  assemblies:
  - Opticon.csp2
  namespace: Opticon
  summary: Basic debug information enabled.
  example: []
  syntax:
    content: Basic = 1
    return:
      type: Opticon.OpnEnvironment.OpnDebugMode
- uid: Opticon.OpnEnvironment.OpnDebugMode.Verbose
  commentId: F:Opticon.OpnEnvironment.OpnDebugMode.Verbose
  id: Verbose
  parent: Opticon.OpnEnvironment.OpnDebugMode
  langs:
  - csharp
  - vb
  name: Verbose
  nameWithType: OpnEnvironment.OpnDebugMode.Verbose
  fullName: Opticon.OpnEnvironment.OpnDebugMode.Verbose
  type: Field
  source:
    id: Verbose
    path: C:\OPN2001\CSP2\Windows\M3188 .Net Wrapper\source\Csp2.net\Opticon.csp2.net\OpnEnvironment.cs
    startLine: 88
  assemblies:
  - Opticon.csp2
  namespace: Opticon
  summary: All debug information enabled (verbose).
  example: []
  syntax:
    content: Verbose = 2
    return:
      type: Opticon.OpnEnvironment.OpnDebugMode
references:
- uid: Opticon
  commentId: N:Opticon
  href: Opticon.html
  name: Opticon
  nameWithType: Opticon
  fullName: Opticon
- uid: Opticon.OpnEnvironment.OpnDebugMode
  commentId: T:Opticon.OpnEnvironment.OpnDebugMode
  parent: Opticon
  href: Opticon.OpnEnvironment.html
  name: OpnEnvironment.OpnDebugMode
  nameWithType: OpnEnvironment.OpnDebugMode
  fullName: Opticon.OpnEnvironment.OpnDebugMode
  spec.csharp:
  - uid: Opticon.OpnEnvironment
    name: OpnEnvironment
    href: Opticon.OpnEnvironment.html
  - name: .
  - uid: Opticon.OpnEnvironment.OpnDebugMode
    name: OpnDebugMode
    href: Opticon.OpnEnvironment.OpnDebugMode.html
  spec.vb:
  - uid: Opticon.OpnEnvironment
    name: OpnEnvironment
    href: Opticon.OpnEnvironment.html
  - name: .
  - uid: Opticon.OpnEnvironment.OpnDebugMode
    name: OpnDebugMode
    href: Opticon.OpnEnvironment.OpnDebugMode.html
