### YamlMime:ConfigFilter

apiRules:
  # Exclude everything in the Opticon.csp2 namespace
  - exclude:
      uidRegex: ^Opticon\.csp2\..*

  # (optional) also exclude the root namespace itself if needed
  - exclude:
      uidRegex: ^Opticon\.csp2$